
superservice:
  image: fabregas/superservice:latest
  labels:
    io.rancher.container.pull_image: always      
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  dns_search:
    - rancher.internal
  volumes:
    - /volumes/$${service_name}:/data


superservice-lb:
  ports:
  - 6600:6600
  tty: true
  image: rancher/load-balancer-service
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  links:
  - superservice:superservice
  stdin_open: true

