
superservice-volume:
  net: none
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  environment:
    - SERVICE_UID=10003
    - SERVICE_GID=10003
    - SERVICE_VOLUME=/data
  volumes:
    - /data
  volume_driver: local
  image: rawmind/alpine-volume:0.0.2-1


superservice:
  image: fabregas/superservice:latest
  labels:
    io.rancher.container.pull_image: always      
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: superservice-volume
  external_links:
    - kafka/broker:kafka-host
    - elastic/elasticsearch-masters:es-host
  dns_search:
    - rancher.internal
  volumes_from:
    - superservice-volume


superservice-lb:
  ports:
  - 6600:6600
  tty: true
  image: rancher/load-balancer-service
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  links:
  - superservice:superservice
  stdin_open: true

