elasticsearch-masters:
  image: fabregas/elastic-conf:5.1.2
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: elasticsearch-base-master
    io.rancher.scheduler.affinity:host_label: es-master=true
  volumes:
    - es_master_conf:/usr/share/elasticsearch/config
    - es_master_bin:/opt/rancher/bin

elasticsearch-base-master:
  labels:
    elasticsearch.master.config.version: '0'
    io.rancher.container.hostname_override: container_name
  environment:
    LOGSPOUT: 'ignore'
  image: fabregas/elastic-xpack:5.1.2
  net: "container:elasticsearch-masters"
  volumes:
    - es_master_data:/usr/share/elasticsearch/data
    - es_master_conf:/usr/share/elasticsearch/config
    - es_master_bin:/opt/rancher/bin
  entrypoint:
    - /opt/rancher/bin/run.sh
  ulimits:
    memlock:
      soft: -1
      hard: -1


elasticsearch-datanodes:
  image: fabregas/elastic-conf:5.1.2
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: elasticsearch-base-datanode
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label: es-data=true
  links:
    - elasticsearch-masters:es-masters
  volumes:
    - es_conf:/usr/share/elasticsearch/config
    - es_bin:/opt/rancher/bin

elasticsearch-base-datanode:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
  environment:
    LOGSPOUT: 'ignore'
  image: fabregas/elastic-xpack:5.1.2
  links:
    - elasticsearch-masters:es-masters
  entrypoint:
    - /opt/rancher/bin/run.sh
  volumes:
    - es_data:/usr/share/elasticsearch/data
    - es_conf:/usr/share/elasticsearch/config
    - es_bin:/opt/rancher/bin
  net: "container:elasticsearch-datanodes"



kopf:
  image: rancher/kopf:v0.4.0
  ports:
    - "80:80"
  environment:
    KOPF_SERVER_NAME: 'es.dev'
    KOPF_ES_SERVERS: 'es-masters:9200'
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: es-master=true
  links:
    - elasticsearch-masters:es-masters


kibana4:
  restart: always
  tty: true
  image: fabregas/kibana-xpack:5.1.2
  ports:
      - "8080:5601"
  stdin_open: true
  environment:
    ELASTICSEARCH_URL: "http://es-masters:9200"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: es-master=true
  links:
    - elasticsearch-masters:es-masters

